services:

  daemon:
    container_name: app_daemon
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "50055:50055"
    volumes:
      - ./configs:/etc/daemon:ro
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50055

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./build/Dockerfile_client
    depends_on:
      - daemon
    volumes:
      - ./configs:/configs:ro
    environment:
      - GRPC_HOST=app_daemon
      - GRPC_PORT=50055
      - LOG_INTERVAL=5
      - DATA_INTERVAL=10