// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SysStatsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogInterval   int32                  `protobuf:"varint,1,opt,name=log_interval,json=logInterval,proto3" json:"log_interval,omitempty"`    // Интервал отправки данных (в секундах)
	DataInterval  int32                  `protobuf:"varint,2,opt,name=data_interval,json=dataInterval,proto3" json:"data_interval,omitempty"` // Период агрегации данных (в секундах)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysStatsStreamRequest) Reset() {
	*x = SysStatsStreamRequest{}
	mi := &file_proto_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysStatsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysStatsStreamRequest) ProtoMessage() {}

func (x *SysStatsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysStatsStreamRequest.ProtoReflect.Descriptor instead.
func (*SysStatsStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *SysStatsStreamRequest) GetLogInterval() int32 {
	if x != nil {
		return x.LogInterval
	}
	return 0
}

func (x *SysStatsStreamRequest) GetDataInterval() int32 {
	if x != nil {
		return x.DataInterval
	}
	return 0
}

type SysStatsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadAverage   float32                `protobuf:"fixed32,1,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	CpuUsage      *CpuUsage              `protobuf:"bytes,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	DiskUsage     *DiskUsage             `protobuf:"bytes,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysStatsStreamResponse) Reset() {
	*x = SysStatsStreamResponse{}
	mi := &file_proto_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysStatsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysStatsStreamResponse) ProtoMessage() {}

func (x *SysStatsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysStatsStreamResponse.ProtoReflect.Descriptor instead.
func (*SysStatsStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *SysStatsStreamResponse) GetLoadAverage() float32 {
	if x != nil {
		return x.LoadAverage
	}
	return 0
}

func (x *SysStatsStreamResponse) GetCpuUsage() *CpuUsage {
	if x != nil {
		return x.CpuUsage
	}
	return nil
}

func (x *SysStatsStreamResponse) GetDiskUsage() *DiskUsage {
	if x != nil {
		return x.DiskUsage
	}
	return nil
}

type CpuUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          float32                `protobuf:"fixed32,1,opt,name=user,proto3" json:"user,omitempty"`
	System        float32                `protobuf:"fixed32,2,opt,name=system,proto3" json:"system,omitempty"`
	Idle          float32                `protobuf:"fixed32,3,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuUsage) Reset() {
	*x = CpuUsage{}
	mi := &file_proto_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuUsage) ProtoMessage() {}

func (x *CpuUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuUsage.ProtoReflect.Descriptor instead.
func (*CpuUsage) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *CpuUsage) GetUser() float32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CpuUsage) GetSystem() float32 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CpuUsage) GetIdle() float32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type DiskUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tps           float32                `protobuf:"fixed32,1,opt,name=tps,proto3" json:"tps,omitempty"`
	KbPs          float32                `protobuf:"fixed32,2,opt,name=kb_ps,json=kbPs,proto3" json:"kb_ps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_proto_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_proto_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *DiskUsage) GetTps() float32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskUsage) GetKbPs() float32 {
	if x != nil {
		return x.KbPs
	}
	return 0
}

var File_proto_daemon_proto protoreflect.FileDescriptor

const file_proto_daemon_proto_rawDesc = "" +
	"\n" +
	"\x12proto/daemon.proto\x12\x06daemon\"_\n" +
	"\x15SysStatsStreamRequest\x12!\n" +
	"\flog_interval\x18\x01 \x01(\x05R\vlogInterval\x12#\n" +
	"\rdata_interval\x18\x02 \x01(\x05R\fdataInterval\"\x9c\x01\n" +
	"\x16SysStatsStreamResponse\x12!\n" +
	"\fload_average\x18\x01 \x01(\x02R\vloadAverage\x12-\n" +
	"\tcpu_usage\x18\x02 \x01(\v2\x10.daemon.CpuUsageR\bcpuUsage\x120\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\v2\x11.daemon.DiskUsageR\tdiskUsage\"J\n" +
	"\bCpuUsage\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x02R\x04user\x12\x16\n" +
	"\x06system\x18\x02 \x01(\x02R\x06system\x12\x12\n" +
	"\x04idle\x18\x03 \x01(\x02R\x04idle\"2\n" +
	"\tDiskUsage\x12\x10\n" +
	"\x03tps\x18\x01 \x01(\x02R\x03tps\x12\x13\n" +
	"\x05kb_ps\x18\x02 \x01(\x02R\x04kbPs2a\n" +
	"\fDaemonStream\x12Q\n" +
	"\x0eSysStatsStream\x12\x1d.daemon.SysStatsStreamRequest\x1a\x1e.daemon.SysStatsStreamResponse0\x01B%Z#github.com/a2gx/daemon/proto;daemonb\x06proto3"

var (
	file_proto_daemon_proto_rawDescOnce sync.Once
	file_proto_daemon_proto_rawDescData []byte
)

func file_proto_daemon_proto_rawDescGZIP() []byte {
	file_proto_daemon_proto_rawDescOnce.Do(func() {
		file_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_daemon_proto_rawDesc), len(file_proto_daemon_proto_rawDesc)))
	})
	return file_proto_daemon_proto_rawDescData
}

var file_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_daemon_proto_goTypes = []any{
	(*SysStatsStreamRequest)(nil),  // 0: daemon.SysStatsStreamRequest
	(*SysStatsStreamResponse)(nil), // 1: daemon.SysStatsStreamResponse
	(*CpuUsage)(nil),               // 2: daemon.CpuUsage
	(*DiskUsage)(nil),              // 3: daemon.DiskUsage
}
var file_proto_daemon_proto_depIdxs = []int32{
	2, // 0: daemon.SysStatsStreamResponse.cpu_usage:type_name -> daemon.CpuUsage
	3, // 1: daemon.SysStatsStreamResponse.disk_usage:type_name -> daemon.DiskUsage
	0, // 2: daemon.DaemonStream.SysStatsStream:input_type -> daemon.SysStatsStreamRequest
	1, // 3: daemon.DaemonStream.SysStatsStream:output_type -> daemon.SysStatsStreamResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_daemon_proto_init() }
func file_proto_daemon_proto_init() {
	if File_proto_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_daemon_proto_rawDesc), len(file_proto_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_daemon_proto_goTypes,
		DependencyIndexes: file_proto_daemon_proto_depIdxs,
		MessageInfos:      file_proto_daemon_proto_msgTypes,
	}.Build()
	File_proto_daemon_proto = out.File
	file_proto_daemon_proto_goTypes = nil
	file_proto_daemon_proto_depIdxs = nil
}
