// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/daemon.proto

package daemon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonStream_SysStatsStream_FullMethodName = "/daemon.DaemonStream/SysStatsStream"
)

// DaemonStreamClient is the client API for DaemonStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonStreamClient interface {
	SysStatsStream(ctx context.Context, in *SysStatsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SysStatsStreamResponse], error)
}

type daemonStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonStreamClient(cc grpc.ClientConnInterface) DaemonStreamClient {
	return &daemonStreamClient{cc}
}

func (c *daemonStreamClient) SysStatsStream(ctx context.Context, in *SysStatsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SysStatsStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonStream_ServiceDesc.Streams[0], DaemonStream_SysStatsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SysStatsStreamRequest, SysStatsStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonStream_SysStatsStreamClient = grpc.ServerStreamingClient[SysStatsStreamResponse]

// DaemonStreamServer is the server API for DaemonStream service.
// All implementations must embed UnimplementedDaemonStreamServer
// for forward compatibility.
type DaemonStreamServer interface {
	SysStatsStream(*SysStatsStreamRequest, grpc.ServerStreamingServer[SysStatsStreamResponse]) error
	mustEmbedUnimplementedDaemonStreamServer()
}

// UnimplementedDaemonStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonStreamServer struct{}

func (UnimplementedDaemonStreamServer) SysStatsStream(*SysStatsStreamRequest, grpc.ServerStreamingServer[SysStatsStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SysStatsStream not implemented")
}
func (UnimplementedDaemonStreamServer) mustEmbedUnimplementedDaemonStreamServer() {}
func (UnimplementedDaemonStreamServer) testEmbeddedByValue()                      {}

// UnsafeDaemonStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonStreamServer will
// result in compilation errors.
type UnsafeDaemonStreamServer interface {
	mustEmbedUnimplementedDaemonStreamServer()
}

func RegisterDaemonStreamServer(s grpc.ServiceRegistrar, srv DaemonStreamServer) {
	// If the following call pancis, it indicates UnimplementedDaemonStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonStream_ServiceDesc, srv)
}

func _DaemonStream_SysStatsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SysStatsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonStreamServer).SysStatsStream(m, &grpc.GenericServerStream[SysStatsStreamRequest, SysStatsStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonStream_SysStatsStreamServer = grpc.ServerStreamingServer[SysStatsStreamResponse]

// DaemonStream_ServiceDesc is the grpc.ServiceDesc for DaemonStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.DaemonStream",
	HandlerType: (*DaemonStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SysStatsStream",
			Handler:       _DaemonStream_SysStatsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/daemon.proto",
}
