name: Daemon System Stats

on:
  push:
    branches: [ master, dev* ]

env:
  GO111MODULE: "on"
  GO_VERSION: 1.24

jobs:
  lint:
    name: Проверка линтером
    runs-on: ubuntu-latest
    steps:
      - name: Получение ветки
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Настройка Go
        uses: actions/setup-go@v3
        with:
          go-version: ~${{ env.GO_VERSION }}

      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Установка golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2

  tests:
    name: Запуск тестов
    runs-on: ubuntu-latest
    steps:
      - name: Получение ветки
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Настройка Go
        uses: actions/setup-go@v3
        with:
          go-version: ~${{ env.GO_VERSION }}

      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Запуск модульных тестов
        run: go test -v -count=1 -race -timeout=1m -coverprofile=coverage.out ./...

      - name: Проверка покрытия кода тестами
        run: go tool cover -html=coverage.out -o coverage.html
