name: Daemon System Stats

on:
  push:
    branches: [ master, dev* ]

env:
  GO111MODULE: "on"
  GO_VERSION: 1.24

jobs:
  lint:
    name: Проверка линтером
    runs-on: ubuntu-latest
    steps:
      - name: Получение ветки
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Настройка Go
        uses: actions/setup-go@v3
        with:
          go-version: ~${{ env.GO_VERSION }}
          cache: true

      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Установка golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.1
          working-directory: ${{ env.BRANCH }}

      - name: Запуск линтера
        run: golangci-lint run ./... --timeout=5m

  build:
    name: Сборка проекта
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Настройка Go
        uses: actions/setup-go@v3
        with:
          go-version: ~${{ env.GO_VERSION }}
          cache: true

      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Загрузка зависимостей
        run: go mod download

      - name: Сборка проекта
        run: go build -v -o bin/app ./cmd/...

      - name: Сохранение артефакта сборки
        uses: actions/upload-artifact@v3
        with:
          name: app-binary
          path: bin/
          retention-days: 7

  tests:
    name: Запуск тестов
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Настройка Go
        uses: actions/setup-go@v3
        with:
          go-version: ~${{ env.GO_VERSION }}
          cache: true

      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Запуск модульных тестов
        run: go test -v -count=1 -race -timeout=1m -coverprofile=coverage.out ./...

      - name: Проверка покрытия кода тестами
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Сохранение отчета о покрытии
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html
          retention-days: 7